name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  oldstable:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          pv \
          curl \
          zstd \
          binfmt-support \
          debootstrap \
          qemu-user-static \
          systemd-container \
          fdisk \
          gcc-arm-linux-gnueabihf

      # - name:  Build Uboot
      #   env:
      #     OS: bullseye
      #   run: | 
      #     echo "OS=bullseye" >> $GITHUB_ENV
      #     git clone --branch $OS --single-branch https://dev.pyra-handheld.com/packages/pyra-uboot && cd pyra-uboot
      #     make -j"$num_cpus" ARCH=arm CROSS_COMPILE="arm-linux-gnueabihf-" omap5_pyra_4gb_defconfig
      #     make -j"$num_cpus" ARCH=arm CROSS_COMPILE="arm-linux-gnueabihf-"
      #     cp u-boot.img ../makeimg_data/uboot/u-boot.img
      #     cp MLO ../makeimg_data/uboot/MLO
      #     tar -cvf ../uboot_bullseye.tar u-boot.img MLO

      - name: Run Makeimg
        env:
          OS: oldstable
        run: |
          echo "OS=oldstable" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-oldstable.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (oldstable - Bullseye)
          path: pyra-oldstable-install.img

      # - name: Upload Artifact
      #   if: ${{ success() }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Uboot (oldstable - Bullseye)
      #     path: uboot_bullseye.tar

  stable:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          pv \
          curl \
          zstd \
          binfmt-support \
          debootstrap \
          qemu-user-static \
          systemd-container \
          fdisk \
          gcc-arm-linux-gnueabihf
      - name:  Build Uboot
        env:
          OS: bookworm
        run: | 
          echo "OS=bookworm" >> $GITHUB_ENV
          git clone --branch $OS --single-branch https://dev.pyra-handheld.com/packages/pyra-uboot && cd pyra-uboot
          make -j"$num_cpus" ARCH=arm CROSS_COMPILE="arm-linux-gnueabihf-" omap5_pyra_4gb_defconfig
          make -j"$num_cpus" ARCH=arm CROSS_COMPILE="arm-linux-gnueabihf-"
          cp u-boot.img ../makeimg_data/uboot/u-boot.img
          cp MLO ../makeimg_data/uboot/MLO
          tar -cvf ../uboot_bookworm.tar u-boot.img MLO

      - name: Run Makeimg
        env:
          OS: bookworm
        run: |
          echo "OS=bookworm" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-stable.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Stable - Bookworm)
          path: pyra-stable-install.img

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: U-Boot (Stable - Bookworm)
          path: uboot_bookworm.tar
      
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Image (Stable - Bookworm)
          path: pyra-stable.img

          

  testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          pv \
          curl \
          zstd \
          binfmt-support \
          debootstrap \
          qemu-user-static \
          systemd-container \
          fdisk
      
      - name: Run Makeimg
        env:
          OS: testing
        run: |
          echo "OS=testing" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-testing.img 4G libz

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Testing)
          path: pyra-testing-install.img

  unstable:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          pv \
          curl \
          zstd \
          binfmt-support \
          debootstrap \
          qemu-user-static \
          systemd-container \
          fdisk
      
      - name: Run Makeimg
        env:
          OS: unstable
        run: |
          echo "OS=unstable" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-sid.img 4G libz
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Unstable)
          path: pyra-sid-install.img