name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  stable:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for multi-platform builds
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build ARMv7 Docker image
        run: |
          docker buildx build --platform linux/arm/v7 -t wally4000/pyrabuild:latest --push .

      - name: Run ARMv7 Docker image
        run: |
          docker run --rm --platform linux/arm/v7 wally4000/pyrabuild:latest

      # - name: Fetch apt repo
      #   run: | 
      #     sudo apt-get update
      #     sudo apt-get install -y \
      #     f2fs-tools \
      #     util-linux \
      #     git \
      #     debootstrap \
      #     systemd-container \
      #     pv \
      #     qemu-user-static \
      #     binfmt-support \
      #     initramfs-tools-core \
      #     curl \
      #     zstd \
      #     fdisk 
      
      - name: Run Makeimg
        env:
          OS: bookworm
        run: |
          echo "OS=boomworm" >> $GITHUB_ENV
          docker run --rm --privileged --platform linux/arm/v7 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            wally4000/pyrabuild:latest \
            ./make_all.sh pyra-stable.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Stable)
          path: pyra-stable-install.img

  testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          debootstrap \
          systemd-container \
          pv \
          qemu-user-static \
          binfmt-support \
          initramfs-tools-core \
          curl \
          zstd \
          fdisk
      
      - name: Run Makeimg
        env:
          OS: testing
        run: |
          sudo update-binfmts --import qemu-arm 
          echo "OS=testing" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-testing.img 4G pyra-meta-base

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Testing)
          path: pyra-testing-install.img

  sid:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          debootstrap \
          systemd-container \
          pv \
          qemu-user-static \
          binfmt-support \
          initramfs-tools-core \
          curl \
          zstd \
          fdisk
      
      - name: Run Makeimg
        env:
          OS: sid
        run: |
          sudo update-binfmts --import qemu-arm 
          echo "OS=sid" >> $GITHUB_ENV
          sudo -E ./make_all.sh pyra-sid.img 4G pyra-meta-base
      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer (Sid)
          path: pyra-sid-install.img