name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          debootstrap \
          systemd-container \
          pv \
          qemu-user-static \
          binfmt-support \
          initramfs-tools-core \
          curl \
          zstd \
          fdisk
      
      - name: Run binfmt update
        run: update-binfmts --enable qemu-arm
      
      - name: Run Makeimg
        run: |
         OS=testing sudo ./make_all.sh pyra.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer
          path: pyra-install.img


  stable:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          debootstrap \
          systemd-container \
          pv \
          qemu-user-static \
          binfmt-support \
          initramfs-tools-core \
          curl \
          zstd \
          fdisk
      
      - name: Run binfmt update
        run: update-binfmts --enable qemu-arm
      
      - name: Run Makeimg
        run: |
         OS=bookworm sudo ./make_all.sh pyra.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer
          path: pyra-install.img

  sid:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Fetch apt repo
        run: | 
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          f2fs-tools \
          util-linux \
          git \
          debootstrap \
          systemd-container \
          pv \
          qemu-user-static \
          binfmt-support \
          initramfs-tools-core \
          curl \
          zstd \
          fdisk
      
      - name: Run binfmt update
        run: update-binfmts --enable qemu-arm
      
      - name: Run Makeimg
        run: |
         OS=sid sudo ./make_all.sh pyra.img 4G pyra-meta-mate

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: PyraOS SD Installer
          path: pyra-install.img